version: "3.7"

services:
  nginx-proxy:
    image: registry.gitlab.com/seka19/docker-images/app/nginx-proxy:0.9.0
    container_name: docker-proxy-nginx
    environment:
      DHPARAM_GENERATION: "false"
    ports:
      - "80:80"
      - "443:443"
      - "6001:6001"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./letsencrypt/certs:/etc/nginx/certs
      - ./letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./letsencrypt/html:/usr/share/nginx/html
      - ./logs/:/var/log/nginx
    networks:
      - docker-proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    container_name: docker-proxy-letsencrypt
    environment:
      DEFAULT_EMAIL: mail@neoways.ru
      NGINX_PROXY_CONTAINER: docker-proxy-nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt/certs:/etc/nginx/certs
      - ./letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./letsencrypt/html:/usr/share/nginx/html

  logrotate:
    image: registry.gitlab.com/seka19/docker-images/app/logrotate:1.3
    container_name: ${COMPOSE_PROJECT_NAME}-logrotate
    restart: always
    environment:
      LOGS_DIRECTORIES: /var/log/nginx
      LOGROTATE_INTERVAL: daily
      LOGROTATE_COPIES: 1
      LOGROTATE_SIZE: 100M
    volumes:
      - ./logs/:/var/log/nginx

networks:
  docker-proxy:
    name: docker-proxy