version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: docker-proxy-nginx
    environment:
      DHPARAM_GENERATION: "false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./letsencrypt/certs:/etc/nginx/certs
      - ./letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./letsencrypt/html:/usr/share/nginx/html
      - ./logs/:/var/log/nginx
      - ./custom.conf:/etc/nginx/conf.d/custom.conf
      - ./Procfile:/app/Procfile
    networks:
      - docker-proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    container_name: docker-proxy-letsencrypt
    environment:
      DEFAULT_EMAIL: mail@neoways.ru
      NGINX_PROXY_CONTAINER: docker-proxy-nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt/certs:/etc/nginx/certs
      - ./letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./letsencrypt/html:/usr/share/nginx/html

networks:
  docker-proxy:
    name: docker-proxy